[package]
name = "BitcoinProjectRust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.29.2"
secp256k1 = "0.25.0"
rand = "0.8.5"